language: ruby
rvm:
  - 2.2.3
install:
  - npm install --dedupe jshint babel babel-cli babel-preset-es2015
  - bundle install
script: bundle exec rake build['acceptance'] unitTests

env:
  matrix:
    - WB_MAPS_API_KEY=AIzaSyBIMixNNyUPrcnsKhRnZu18Ue5MqtT0aOY
  global:
    secure: M5/zSQ8ULSbmtZv715BHqwarMufKtlNnVi5HdOrV3jO9B/TH80QFZyj0OfwSIRcFO5koPSuOgoBvdtHMOVkiTU7jpxELmgb8WWy1OHNEoROPx5QiYuLhI16v7LG4fYQUgdxWhxucL64Q6x6uv8DTPSJJpCCCkT/eFiVR4Bn39eLHiFH8a8WWFla3GCy1BVtT3hxq9Mr3bLzgBeBHlUOb8kTxiCi2btLjEyYCIUx9tMsSEep9nPnrgGu9N39zOYXLo7OvUiKmINfH+qq7rdum19x/6gvW7/H9KLvKw50kA4uOznE99+Kq8dJX64ynuR73p3V46D9mUz/A3jBavmfiRSJuBtNnyipGh+PEjUBHL6wxt22NNhej86Z+RlzxbtWIYaPlCn66yJpjGDy2A7efpL15+HxdX+DsPWQdjrmwafE5D2wNewhU1mE8N6QYEi+02SNeC6A74/wpVStBPGOLOr/pCbwqbESKvapinzAfE33SwAkjedeVJYcPAD5XYID4GWmsW+arPc3vWISJO2Q7tnd1dmrxqme77hIdWLNQOoTyLd/Znq7o20NFUi+8ZBRDBKGtmN8UVs/Giiv5R4J9pEsSsFmAqwhZ0o8WP+Z4lS7fAtNKsM9EbHrTijUm3udR4XvkONx0M/hJc2iDj/PpsyLCE7xYqC5wK9hZ9FLpULo=

deploy:
  edge: true
  provider: cloudfoundry
  username: kseebaldt+cfdeploy@pivotal.io
  password:
    secure: I+x9siGLzN3BTvL+cIlsuTflwToYa9BV7ubXFFG/ZziS2RPm+eX+9ctJ6lUms2hFF9dmdZY4WWOfgnnlWb2XCW+ZUlPXkJxvE9jSuXQ8mqMJpVXxrEUsE2ifyOo84DFE4PXDDqnSg75LKKrf/Oc9fy+3IpqEKVhT6+4jxU3pNfLgRrO4Eygmx9ME983A2cjqQlTF5BA/IG9hnn4nBNTaD3YWB+DYAeb0ormFKZDj2xgvRoJvVx7z1MQSE/ibj67R6D879g4MP9qcDV2frAEC8CZGNnFa28GwRj7F9YI1PJ1wwbA84SH8Uqm1Zj2q/PwvW7ueqmWsfcYFQfsL4VqevYUu8eXj+IQRCSBSwLwKQx8D3EebyUv9uXUJuD1AMEwJjL56IYwx8R3oltFYVeYTaGOMPDJIk4mEIWTymZLkWsJLfwkQzEA7XraHq8KTvqdknFjsVHOh7poSOM78nNVPez/bw3rviMJCo2qboLsxbPSUX4fvgGZlnSTm1wbZzo+u3jBv7S0xuqP827YTW3f/qxKyISIKqhL7hMYXSYnYRlMTP+n756P1zRTyD0W6Oh9kJjfCQA8AZ0kme/boJTE4U29Vd/uxm7d4j7cA/M7rqj9YAn5dy/3aiIUeu4+gnFj8vYoqsnb2BV02TUbTghePJHciBQ8Md5CWTMuXb2u+1a4=
  api: https://api.run.pivotal.io
  organization: seattle-beach
  space: weatherbus-dev

after_success:
  - bundle exec rake run_integration
