---
platform: linux
image: "docker:///alidaka/web-frontend-test"
inputs:
  - name: web
outputs:
  - name: build
    path: web/target
run:
  path: "web/concourse/build_and_test.sh"
  args: ["web"]
params:
  "TERM": "xterm"

