---
platform: linux
image: "docker:///alidaka/web-frontend-test"
inputs:
  - name: weatherbus-web
outputs:
  - name: build
    path: weatherbus-web/artifacts
run:
  path: "weatherbus-web/concourse/build_and_test.sh"
  args: ["weatherbus-web"]
params:
  "TERM": "xterm"

